package com.example.restservice;
/* Generated by opensource COBOL 4J 1.0.22 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import java.util.Optional;
import java.lang.NullPointerException;
import java.lang.IndexOutOfBoundsException;

public class LOANSUB implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule cobolCurrentModule;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return LOANSUB_(0, argStorages);
  }

  @Override
  public void cancel() {
    LOANSUB_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute (int LK_LOAN, double LK_INTEREST_RATE, int LK_PERIODS, int LK_PAYMENT) {
    this.f_LK_LOAN.setDataStorage(new CobolDataStorage(9));
    this.f_LK_LOAN.moveFrom(LK_LOAN);
    this.b_LK_LOAN = this.f_LK_LOAN.getDataStorage();
    this.f_LK_INTEREST_RATE.setDataStorage(new CobolDataStorage(5));
    this.f_LK_INTEREST_RATE.moveFrom(LK_INTEREST_RATE);
    this.b_LK_INTEREST_RATE = this.f_LK_INTEREST_RATE.getDataStorage();
    this.f_LK_PERIODS.setDataStorage(new CobolDataStorage(3));
    this.f_LK_PERIODS.moveFrom(LK_PERIODS);
    this.b_LK_PERIODS = this.f_LK_PERIODS.getDataStorage();
    this.f_LK_PAYMENT.setDataStorage(new CobolDataStorage(9));
    this.f_LK_PAYMENT.moveFrom(LK_PAYMENT);
    this.b_LK_PAYMENT = this.f_LK_PAYMENT.getDataStorage();
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode,
      new CobolResultInt(f_LK_LOAN.getInt()),
      new CobolResultDouble(f_LK_INTEREST_RATE.getDouble()),
      new CobolResultInt(f_LK_PERIODS.getInt()),
      new CobolResultInt(f_LK_PAYMENT.getInt())
    );
  }

  public int LOANSUB_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    this.b_LK_LOAN = 0 < argStorages.length ? argStorages[0] : null;
    this.b_LK_INTEREST_RATE = 1 < argStorages.length ? argStorages[1] : null;
    this.b_LK_PERIODS = 2 < argStorages.length ? argStorages[2] : null;
    this.b_LK_PAYMENT = 3 < argStorages.length ? argStorages[3] : null;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	d0.clear();
    	d0.setScale(0);
    	d1.clear();
    	d1.setScale(0);
    	d2.clear();
    	d2.setScale(0);
    	d3.clear();
    	d3.setScale(0);
    	d4.clear();
    	d4.setScale(0);
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("LOANSUB");

      /* Initialize decimal numbers */
      d0.decimalInit();
      d1.decimalInit();
      d2.decimalInit();
      d3.decimalInit();
      d4.decimalInit();

      b_RETURN_CODE.set((int)0);
      b_WK_INTEREST_RATE.fillBytes('0', 5);
      b_WK_INTEREST_YEAR.fillBytes('0', 11);
      b_WK_INTEREST_MONTH.fillBytes('0', 11);
      b_WK_PERIODS.fillBytes('0', 3);
      b_WK_PAYMENT.fillBytes('0', 9);
      b_WK_LOAN.fillBytes('0', 18);
      b_WK_LOAN_LEFT.fillBytes('0', 18);
      b_WK_PRINCIPAL.fillBytes('0', 9);
      b_WK_INTEREST.fillBytes('0', 9);
      b_WK_PERIODS_CNT.fillBytes('0', 3);
      b_WK_DATE.fillBytes('0', 8);
      b_WK_KAKUNIN.setByte(' ');
      f_DSP_PAYMENT.moveFrom (CobolConstant.zero);
      f_DSP_PRINCIPAL.moveFrom (CobolConstant.zero);
      f_DSP_INTEREST.moveFrom (CobolConstant.zero);
      f_DSP_LOAN_LEFT.moveFrom (CobolConstant.zero);
      f_DSP_PERIODS_CNT.moveFrom (CobolConstant.zero);
      b_DSP_YEAR.fillBytes('0', 4);
      b_DSP_MONTH.fillBytes('0', 2);
      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      CobolStopRunException.dummy();
      CobolGoBackException.dummy();
      /* Entry dispatch */
      execEntry(l_LOANSUB);

    } catch(CobolGoBackException e) {
      return e.getReturnCode();
    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolGoBackException, CobolStopRunException {

        return Optional.of(contList[l_LOANSUB]);
      }
    },
    /* Entry LOANSUB */
    new CobolControl(l_LOANSUB, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolGoBackException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN_SECTION, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolGoBackException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__HAJIME]);
      }
    },
    /* HAJIME */
    new CobolControl(l_MAIN_SECTION__HAJIME, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolGoBackException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__MAIN_000]);
      }
    },
    /* MAIN-000 */
    new CobolControl(l_MAIN_SECTION__MAIN_000, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolGoBackException, CobolStopRunException {
        /* LOANSUB.cbl:64: MOVE */
        {
          f_WK_LOAN.moveFrom (new GetAbstractCobolField() {
            public AbstractCobolField run() {
              f_LK_LOAN.setDataStorage(b_LK_LOAN);
              return f_LK_LOAN;
            }
          }.run());
        }
        /* LOANSUB.cbl:65: MOVE */
        {
          b_WK_INTEREST_RATE.setBytes (b_LK_INTEREST_RATE, 5);
        }
        /* LOANSUB.cbl:66: MOVE */
        {
          b_WK_PERIODS.setBytes (b_LK_PERIODS, 3);
        }

        return Optional.of(contList[l_MAIN_SECTION__MAIN_100]);
      }
    },
    /* MAIN-100 */
    new CobolControl(l_MAIN_SECTION__MAIN_100, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolGoBackException, CobolStopRunException {
        /* LOANSUB.cbl:68: COMPUTE */
        {
          {
            {
              d0.setField (f_WK_INTEREST_RATE);
              d1.set (100);
              d0.div (d1);
              d0.getField (f_WK_INTEREST_YEAR, 4);
            }
          }
        }
        /* LOANSUB.cbl:69: COMPUTE */
        {
          {
            {
              d0.setField (f_WK_INTEREST_YEAR);
              d1.set (12);
              d0.div (d1);
              d0.getField (f_WK_INTEREST_MONTH, 4);
            }
          }
        }
        /* LOANSUB.cbl:70: COMPUTE */
        {
          {
            {
              d0.setField (f_WK_LOAN);
              d3.setField (f_WK_INTEREST_MONTH);
              d0.mul (d3);
              d2.set (1);
              d4.setField (f_WK_INTEREST_MONTH);
              d2.add (d4);
              d3.set (b_WK_PERIODS.getNumdisp(3));
              d2.pow (d3);
              d0.mul (d2);
              d1.set (1);
              d4.setField (f_WK_INTEREST_MONTH);
              d1.add (d4);
              d3.set (b_WK_PERIODS.getNumdisp(3));
              d1.pow (d3);
              d2.set (1);
              d1.sub (d2);
              d0.div (d1);
              d0.getField (f_WK_PAYMENT, 5);
            }
          }
        }
        /* LOANSUB.cbl:74: MOVE */
        {
          b_LK_PAYMENT.setBytes (b_WK_PAYMENT, 9);
        }
        /* LOANSUB.cbl:75: GO TO */
        {
          if(true) return Optional.of(contList[l_MAIN_SECTION__OWARI          ]);

        }

        return Optional.of(contList[l_MAIN_SECTION__MAIN_200]);
      }
    },
    /* MAIN-200 */
    new CobolControl(l_MAIN_SECTION__MAIN_200, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolGoBackException, CobolStopRunException {
        /* LOANSUB.cbl:77: DISPLAY */
        {
          CobolTerminal.display (0, 0, 1, c_1);
        }
        /* LOANSUB.cbl:78: MOVE */
        {
          f_DSP_PAYMENT.moveFrom (f_WK_PAYMENT);
        }
        /* LOANSUB.cbl:79: DISPLAY */
        {
          CobolTerminal.display (0, 1, 1, f_DSP_PAYMENT);
        }
        /* LOANSUB.cbl:80: DISPLAY */
        {
          CobolTerminal.display (0, 1, 1, c_2);
        }
        /* LOANSUB.cbl:81: ACCEPT */
        {
          CobolTerminal.accept (f_WK_KAKUNIN);
        }
        /* LOANSUB.cbl:82: IF */
        {
          if (((long)(Byte.toUnsignedInt(b_WK_KAKUNIN.getByte(0)) - (int)89) != 0L))
            {
              /* LOANSUB.cbl:83: GO TO */
              {
                if(true) return Optional.of(contList[l_MAIN_SECTION__OWARI                ]);

              }
            }
        }

        return Optional.of(contList[l_MAIN_SECTION__MAIN_300]);
      }
    },
    /* MAIN-300 */
    new CobolControl(l_MAIN_SECTION__MAIN_300, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolGoBackException, CobolStopRunException {
        /* LOANSUB.cbl:85: MOVE */
        {
          b_WK_LOAN_LEFT.setBytes (b_WK_LOAN, 18);
        }
        /* LOANSUB.cbl:86: MOVE */
        {
          b_WK_PERIODS_CNT.setBytes (str_0_001, 3);
        }
        /* LOANSUB.cbl:87: ACCEPT */
        {
          CobolTerminal.acceptDate_yyyymmdd (f_WK_DATE);
        }
        /* LOANSUB.cbl:89: DISPLAY */
        {
          CobolTerminal.display (0, 1, 1, c_3_NO);
        }
        /* LOANSUB.cbl:91: DISPLAY */
        {
          CobolTerminal.display (0, 1, 1, c_4);
        }

        return Optional.of(contList[l_MAIN_SECTION__MAIN_210]);
      }
    },
    /* MAIN-210 */
    new CobolControl(l_MAIN_SECTION__MAIN_210, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolGoBackException, CobolStopRunException {
        /* LOANSUB.cbl:94: COMPUTE */
        {
          {
            {
              d0.setField (f_WK_LOAN_LEFT);
              d1.setField (f_WK_INTEREST_MONTH);
              d0.mul (d1);
              d0.getField (f_WK_INTEREST, 5);
            }
          }
        }
        /* LOANSUB.cbl:96: COMPUTE */
        {
          {
            {
              d0.set (b_WK_PAYMENT.getNumdisp(9));
              d1.set (b_WK_INTEREST.getNumdisp(9));
              d0.sub (d1);
              d0.getField (f_WK_PRINCIPAL, 4);
            }
          }
        }
        /* LOANSUB.cbl:97: COMPUTE */
        {
          {
            {
              d0.setField (f_WK_LOAN_LEFT);
              d1.set (b_WK_PRINCIPAL.getNumdisp(9));
              d0.sub (d1);
              d0.getField (f_WK_LOAN_LEFT, 4);
            }
          }
        }
        /* LOANSUB.cbl:98: IF */
        {
          if (((long)b_WK_PERIODS_CNT.memcmp (b_WK_PERIODS, 3) == 0L))
            {
              /* LOANSUB.cbl:99: ADD */
              {
                f_WK_PRINCIPAL.add (f_WK_LOAN_LEFT, 4);
                f_WK_PAYMENT.add (f_WK_LOAN_LEFT, 4);
              }
              /* LOANSUB.cbl:101: MOVE */
              {
                b_WK_LOAN_LEFT.fillBytes (48, 18);
              }
            }
        }
        /* LOANSUB.cbl:102: MOVE */
        {
          f_DSP_PERIODS_CNT.moveFrom (f_WK_PERIODS_CNT);
        }
        /* LOANSUB.cbl:103: MOVE */
        {
          f_DSP_PAYMENT.moveFrom (f_WK_PAYMENT);
        }
        /* LOANSUB.cbl:104: MOVE */
        {
          f_DSP_INTEREST.moveFrom (f_WK_INTEREST);
        }
        /* LOANSUB.cbl:105: MOVE */
        {
          f_DSP_PRINCIPAL.moveFrom (f_WK_PRINCIPAL);
        }
        /* LOANSUB.cbl:106: MOVE */
        {
          f_DSP_LOAN_LEFT.moveFrom (f_WK_LOAN_LEFT);
        }
        /* LOANSUB.cbl:107: DISPLAY */
        {
          CobolTerminal.display (0, 1, 13, f_WK_PERIODS_CNT, c_5, f_WK_YEAR__WK_DATE, c_6, f_WK_MONTH__WK_DATE, c_5, f_DSP_PAYMENT, c_5, f_DSP_PRINCIPAL, c_5, f_DSP_INTEREST, c_5, f_DSP_LOAN_LEFT);
        }
        /* LOANSUB.cbl:111: COMPUTE */
        {
          {
            {
              d0.set (b_WK_PERIODS_CNT.getNumdisp(3));
              d1.set (1);
              d0.add (d1);
              d0.getField (f_WK_PERIODS_CNT, 4);
            }
          }
        }
        /* LOANSUB.cbl:112: IF */
        {
          if (((long)b_WK_MONTH__WK_DATE.cmpNumdisp (2, 12) == 0L))
            {
              /* LOANSUB.cbl:113: MOVE */
              {
                b_WK_MONTH__WK_DATE.setBytes (str_1_01, 2);
              }
              /* LOANSUB.cbl:114: ADD */
              {
                f_WK_YEAR__WK_DATE.add (c_7_1, 4);
              }
            }
          else
            {
              /* LOANSUB.cbl:116: ADD */
              {
                f_WK_MONTH__WK_DATE.add (c_7_1, 4);
              }
            }
        }
        /* LOANSUB.cbl:117: IF */
        {
          if (((long)b_WK_PERIODS_CNT.memcmp (b_WK_PERIODS, 3) >  0L))
            {
              /* LOANSUB.cbl:118: GO TO */
              {
                if(true) return Optional.of(contList[l_MAIN_SECTION__OWARI                ]);

              }
            }
        }
        /* LOANSUB.cbl:119: GO TO */
        {
          if(true) return Optional.of(contList[l_MAIN_SECTION__MAIN_210          ]);

        }

        return Optional.of(contList[l_MAIN_SECTION__OWARI]);
      }
    },
    /* OWARI */
    new CobolControl(l_MAIN_SECTION__OWARI, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolGoBackException, CobolStopRunException {
        /* LOANSUB.cbl:122: GOBACK */
        {
          if(true) return Optional.of(contList[contList.length - 1]);
        }
        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolGoBackException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new LOANSUB().LOANSUB_(0);
    CobolStopRunException.stopRun();
  }

  public LOANSUB()
  {
    init();
  }

  public void init() 
  {
    try {
      /* Decimal structures */

      d0 = new CobolDecimal();
      d1 = new CobolDecimal();
      d2 = new CobolDecimal();
      d3 = new CobolDecimal();
      d4 = new CobolDecimal();

      /* Data storage */

      cob_unifunc = null;

      /* PROGRAM-ID : LOANSUB */
      b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
      b_WK_INTEREST_RATE = new CobolDataStorage(5);	/* WK-INTEREST-RATE */
      b_WK_INTEREST_YEAR = new CobolDataStorage(11);	/* WK-INTEREST-YEAR */
      b_WK_INTEREST_MONTH = new CobolDataStorage(11);	/* WK-INTEREST-MONTH */
      b_WK_PERIODS = new CobolDataStorage(3);	/* WK-PERIODS */
      b_WK_PAYMENT = new CobolDataStorage(9);	/* WK-PAYMENT */
      b_WK_LOAN = new CobolDataStorage(18);	/* WK-LOAN */
      b_WK_LOAN_LEFT = new CobolDataStorage(18);	/* WK-LOAN-LEFT */
      b_WK_PRINCIPAL = new CobolDataStorage(9);	/* WK-PRINCIPAL */
      b_WK_INTEREST = new CobolDataStorage(9);	/* WK-INTEREST */
      b_WK_PERIODS_CNT = new CobolDataStorage(3);	/* WK-PERIODS-CNT */
      b_WK_DATE = new CobolDataStorage(8);	/* WK-DATE */
      b_WK_KAKUNIN = new CobolDataStorage(1);	/* WK-KAKUNIN */
      b_DSP_PAYMENT = new CobolDataStorage(11);	/* DSP-PAYMENT */
      b_DSP_PRINCIPAL = new CobolDataStorage(11);	/* DSP-PRINCIPAL */
      b_DSP_INTEREST = new CobolDataStorage(11);	/* DSP-INTEREST */
      b_DSP_LOAN_LEFT = new CobolDataStorage(11);	/* DSP-LOAN-LEFT */
      b_DSP_PERIODS_CNT = new CobolDataStorage(3);	/* DSP-PERIODS-CNT */
      b_DSP_YEAR = new CobolDataStorage(4);	/* DSP-YEAR */
      b_DSP_MONTH = new CobolDataStorage(2);	/* DSP-MONTH */
      b_WK_MONTH__WK_DATE = b_WK_DATE.getSubDataStorage(4);
      b_WK_YEAR__WK_DATE = b_WK_DATE;

      /* End of data storage */


      initAttr();

      /* Fields */

      /* PROGRAM-ID : LOANSUB */
      f_WK_INTEREST_RATE	= CobolFieldFactory.makeCobolField(5, b_WK_INTEREST_RATE, a_5);	/* WK-INTEREST-RATE */
      f_WK_INTEREST_YEAR	= CobolFieldFactory.makeCobolField(11, b_WK_INTEREST_YEAR, a_6);	/* WK-INTEREST-YEAR */
      f_WK_INTEREST_MONTH	= CobolFieldFactory.makeCobolField(11, b_WK_INTEREST_MONTH, a_6);	/* WK-INTEREST-MONTH */
      f_WK_PAYMENT	= CobolFieldFactory.makeCobolField(9, b_WK_PAYMENT, a_4);	/* WK-PAYMENT */
      f_WK_LOAN	= CobolFieldFactory.makeCobolField(18, b_WK_LOAN, a_3);	/* WK-LOAN */
      f_WK_LOAN_LEFT	= CobolFieldFactory.makeCobolField(18, b_WK_LOAN_LEFT, a_3);	/* WK-LOAN-LEFT */
      f_WK_PRINCIPAL	= CobolFieldFactory.makeCobolField(9, b_WK_PRINCIPAL, a_4);	/* WK-PRINCIPAL */
      f_WK_INTEREST	= CobolFieldFactory.makeCobolField(9, b_WK_INTEREST, a_4);	/* WK-INTEREST */
      f_WK_PERIODS_CNT	= CobolFieldFactory.makeCobolField(3, b_WK_PERIODS_CNT, a_9);	/* WK-PERIODS-CNT */
      f_WK_DATE	= CobolFieldFactory.makeCobolField(8, b_WK_DATE, a_8);	/* WK-DATE */
      f_WK_YEAR__WK_DATE	= CobolFieldFactory.makeCobolField(4, b_WK_YEAR__WK_DATE, a_10);	/* WK-YEAR */
      f_WK_MONTH__WK_DATE	= CobolFieldFactory.makeCobolField(2, b_WK_MONTH__WK_DATE, a_11);	/* WK-MONTH */
      f_WK_KAKUNIN	= CobolFieldFactory.makeCobolField(1, b_WK_KAKUNIN, a_7);	/* WK-KAKUNIN */
      f_DSP_PAYMENT	= CobolFieldFactory.makeCobolField(11, b_DSP_PAYMENT, a_1);	/* DSP-PAYMENT */
      f_DSP_PRINCIPAL	= CobolFieldFactory.makeCobolField(11, b_DSP_PRINCIPAL, a_1);	/* DSP-PRINCIPAL */
      f_DSP_INTEREST	= CobolFieldFactory.makeCobolField(11, b_DSP_INTEREST, a_1);	/* DSP-INTEREST */
      f_DSP_LOAN_LEFT	= CobolFieldFactory.makeCobolField(11, b_DSP_LOAN_LEFT, a_1);	/* DSP-LOAN-LEFT */
      f_DSP_PERIODS_CNT	= CobolFieldFactory.makeCobolField(3, b_DSP_PERIODS_CNT, a_2);	/* DSP-PERIODS-CNT */
      f_LK_LOAN	= CobolFieldFactory.makeCobolField(9, (CobolDataStorage)null, a_4);	/* LK-LOAN */

      /* End of fields */


      /* Call parameters */
      f_LK_PAYMENT = CobolFieldFactory.makeCobolField(9, (CobolDataStorage)null, a_4);
      f_LK_PERIODS = CobolFieldFactory.makeCobolField(3, (CobolDataStorage)null, a_9);
      f_LK_INTEREST_RATE = CobolFieldFactory.makeCobolField(5, (CobolDataStorage)null, a_5);
      /* Constants */

      c_1	= CobolFieldFactory.makeCobolField(17, str_2, a_7);
      c_2	= CobolFieldFactory.makeCobolField(24, str_3, a_7);
      c_3_NO	= CobolFieldFactory.makeCobolField(65, str_4_NO, a_7);
      c_4	= CobolFieldFactory.makeCobolField(59, str_5, a_7);
      c_5	= CobolFieldFactory.makeCobolField(1, str_6, a_7);
      c_6	= CobolFieldFactory.makeCobolField(1, str_7, a_7);
      c_7_1	= CobolFieldFactory.makeCobolField(1, "1", a_12);

    } catch(NullPointerException e) {
      System.out.println("Error - NullpointerException");
    } catch(IndexOutOfBoundsException e) {
      System.out.println("Error - IndexOutOfBoundsException");
    }
  }

  private void initAttr() {
    /* Attributes */

    a_1 = new CobolFieldAttribute (36, 9, 0, 0, "Z\003\000\000\000,\001\000\000\000Z\003\000\000\000,\001\000\000\000Z\002\000\000\0009\001\000\000\000");
    a_2 = new CobolFieldAttribute (36, 3, 0, 0, "Z\002\000\000\0009\001\000\000\000");
    a_3 = new CobolFieldAttribute (16, 18, 9, 0, null);
    a_4 = new CobolFieldAttribute (16, 9, 0, 0, null);
    a_5 = new CobolFieldAttribute (16, 5, 3, 0, null);
    a_6 = new CobolFieldAttribute (16, 11, 9, 0, null);
    a_7 = new CobolFieldAttribute (33, 0, 0, 0, null);
    a_8 = new CobolFieldAttribute (1, 0, 0, 0, null);
    a_9 = new CobolFieldAttribute (16, 3, 0, 0, null);
    a_10 = new CobolFieldAttribute (16, 4, 0, 0, null);
    a_11 = new CobolFieldAttribute (16, 2, 0, 0, null);
    a_12 = new CobolFieldAttribute (16, 1, 0, 0, null);

  }

  /* Decimal structures */

  private CobolDecimal d0;
  private CobolDecimal d1;
  private CobolDecimal d2;
  private CobolDecimal d3;
  private CobolDecimal d4;

  /* Data storage */

  /* PROGRAM-ID : LOANSUB */
  private CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_WK_INTEREST_RATE;	/* WK-INTEREST-RATE */
  private CobolDataStorage b_WK_INTEREST_YEAR;	/* WK-INTEREST-YEAR */
  private CobolDataStorage b_WK_INTEREST_MONTH;	/* WK-INTEREST-MONTH */
  private CobolDataStorage b_WK_PERIODS;	/* WK-PERIODS */
  private CobolDataStorage b_WK_PAYMENT;	/* WK-PAYMENT */
  private CobolDataStorage b_WK_LOAN;	/* WK-LOAN */
  private CobolDataStorage b_WK_LOAN_LEFT;	/* WK-LOAN-LEFT */
  private CobolDataStorage b_WK_PRINCIPAL;	/* WK-PRINCIPAL */
  private CobolDataStorage b_WK_INTEREST;	/* WK-INTEREST */
  private CobolDataStorage b_WK_PERIODS_CNT;	/* WK-PERIODS-CNT */
  private CobolDataStorage b_WK_DATE;	/* WK-DATE */
  private CobolDataStorage b_WK_KAKUNIN;	/* WK-KAKUNIN */
  private CobolDataStorage b_DSP_PAYMENT;	/* DSP-PAYMENT */
  private CobolDataStorage b_DSP_PRINCIPAL;	/* DSP-PRINCIPAL */
  private CobolDataStorage b_DSP_INTEREST;	/* DSP-INTEREST */
  private CobolDataStorage b_DSP_LOAN_LEFT;	/* DSP-LOAN-LEFT */
  private CobolDataStorage b_DSP_PERIODS_CNT;	/* DSP-PERIODS-CNT */
  private CobolDataStorage b_DSP_YEAR;	/* DSP-YEAR */
  private CobolDataStorage b_DSP_MONTH;	/* DSP-MONTH */
  private CobolDataStorage b_WK_MONTH__WK_DATE;
  private CobolDataStorage b_WK_YEAR__WK_DATE;

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : LOANSUB */
  private AbstractCobolField f_WK_INTEREST_RATE;	/* WK-INTEREST-RATE */
  private AbstractCobolField f_WK_INTEREST_YEAR;	/* WK-INTEREST-YEAR */
  private AbstractCobolField f_WK_INTEREST_MONTH;	/* WK-INTEREST-MONTH */
  private AbstractCobolField f_WK_PAYMENT;	/* WK-PAYMENT */
  private AbstractCobolField f_WK_LOAN;	/* WK-LOAN */
  private AbstractCobolField f_WK_LOAN_LEFT;	/* WK-LOAN-LEFT */
  private AbstractCobolField f_WK_PRINCIPAL;	/* WK-PRINCIPAL */
  private AbstractCobolField f_WK_INTEREST;	/* WK-INTEREST */
  private AbstractCobolField f_WK_PERIODS_CNT;	/* WK-PERIODS-CNT */
  private AbstractCobolField f_WK_DATE;	/* WK-DATE */
  private AbstractCobolField f_WK_YEAR__WK_DATE;	/* WK-YEAR */
  private AbstractCobolField f_WK_MONTH__WK_DATE;	/* WK-MONTH */
  private AbstractCobolField f_WK_KAKUNIN;	/* WK-KAKUNIN */
  private AbstractCobolField f_DSP_PAYMENT;	/* DSP-PAYMENT */
  private AbstractCobolField f_DSP_PRINCIPAL;	/* DSP-PRINCIPAL */
  private AbstractCobolField f_DSP_INTEREST;	/* DSP-INTEREST */
  private AbstractCobolField f_DSP_LOAN_LEFT;	/* DSP-LOAN-LEFT */
  private AbstractCobolField f_DSP_PERIODS_CNT;	/* DSP-PERIODS-CNT */
  private AbstractCobolField f_LK_LOAN;	/* LK-LOAN */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Constants */

  private AbstractCobolField c_7_1;
  private AbstractCobolField c_6;
  private AbstractCobolField c_5;
  private AbstractCobolField c_4;
  private AbstractCobolField c_3_NO;
  private AbstractCobolField c_2;
  private AbstractCobolField c_1;

  /* Attributes */

  private CobolFieldAttribute a_12;
  private CobolFieldAttribute a_11;
  private CobolFieldAttribute a_10;
  private CobolFieldAttribute a_9;
  private CobolFieldAttribute a_8;
  private CobolFieldAttribute a_7;
  private CobolFieldAttribute a_6;
  private CobolFieldAttribute a_5;
  private CobolFieldAttribute a_4;
  private CobolFieldAttribute a_3;
  private CobolFieldAttribute a_2;
  private CobolFieldAttribute a_1;

  /* Call parameters */
  private AbstractCobolField f_LK_PAYMENT;
  private CobolDataStorage b_LK_PAYMENT;
  private AbstractCobolField f_LK_PERIODS;
  private CobolDataStorage b_LK_PERIODS;
  private AbstractCobolField f_LK_INTEREST_RATE;
  private CobolDataStorage b_LK_INTEREST_RATE;
  private CobolDataStorage b_LK_LOAN;


  /* String literals */
  public static final byte[] str_7 = CobolUtil.stringToBytes("/");
  public static final byte[] str_6 = CobolUtil.stringToBytes(" ");
  public static final byte[] str_5 = CobolUtil.stringToBytes("--- ------- ----------- ----------- ----------- -----------");
  public static final byte[] str_4_NO = CobolUtil.toBytes((byte)0x4e, (byte)0x4f, (byte)0x20, (byte)0x20, (byte)0xe5, (byte)0xb9, (byte)0xb4, (byte)0xe6, (byte)0x9c, (byte)0x88, (byte)0x20, (byte)0x20, (byte)0x20, (byte)0x20, (byte)0xe6, (byte)0x94, (byte)0xaf, (byte)0xe6, (byte)0x89, (byte)0x95, (byte)0x20, (byte)0x20, (byte)0x20, (byte)0x20, (byte)0x20, (byte)0x20, (byte)0x20, (byte)0x20, (byte)0xe5, (byte)0x8e, (byte)0x9f, (byte)0xe6, (byte)0x9c, (byte)0xac, (byte)0x20, (byte)0x20, (byte)0x20, (byte)0x20, (byte)0x20, (byte)0x20, (byte)0x20, (byte)0x20, (byte)0xe5, (byte)0x88, (byte)0xa9, (byte)0xe6, (byte)0x81, (byte)0xaf, (byte)0x20, (byte)0x20, (byte)0x20, (byte)0x20, (byte)0x20, (byte)0x20, (byte)0x20, (byte)0x20, (byte)0xe6, (byte)0xae, (byte)0x8b, (byte)0xe5, (byte)0x85, (byte)0x83, (byte)0xe9, (byte)0x87, (byte)0x91);
  public static final byte[] str_3 = CobolUtil.toBytes((byte)0xe5, (byte)0x8d, (byte)0xb0, (byte)0xe5, (byte)0x88, (byte)0xb7, (byte)0xe3, (byte)0x81, (byte)0x97, (byte)0xe3, (byte)0x81, (byte)0xbe, (byte)0xe3, (byte)0x81, (byte)0x99, (byte)0xe3, (byte)0x81, (byte)0x8b, (byte)0x3f, (byte)0x28, (byte)0x59, (byte)0x2f, (byte)0x4e, (byte)0x29);
  public static final byte[] str_2 = CobolUtil.toBytes((byte)0xe8, (byte)0xbf, (byte)0x94, (byte)0xe6, (byte)0xb8, (byte)0x88, (byte)0xe9, (byte)0xa1, (byte)0x8d, (byte)0x28, (byte)0xe6, (byte)0x9c, (byte)0x88, (byte)0x29, (byte)0x20, (byte)0x3d, (byte)0x20);
  public static final byte[] str_1_01 = CobolUtil.stringToBytes("01");
  public static final byte[] str_0_001 = CobolUtil.stringToBytes("001");

  /* Sections and Labels */
  private final static int l_LOANSUB = 1;
  private final static int l_MAIN_SECTION = 2;
  private final static int l_MAIN_SECTION__HAJIME = 3;
  private final static int l_MAIN_SECTION__MAIN_000 = 4;
  private final static int l_MAIN_SECTION__MAIN_100 = 5;
  private final static int l_MAIN_SECTION__MAIN_200 = 6;
  private final static int l_MAIN_SECTION__MAIN_300 = 7;
  private final static int l_MAIN_SECTION__MAIN_210 = 8;
  private final static int l_MAIN_SECTION__OWARI = 9;
  private final static int l_Default_Error_Handler = 10;

}
